# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ inputs, ... }: {
  flake.nixosModules.vestaHardware = { config, lib, pkgs, modulesPath, ... }: {
    imports = [
	  (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  	boot.initrd.kernelModules = [ ];
	boot.kernelModules = [ "kvm-intel" ];
	boot.extraModulePackages = [ ];

	fileSystems."/" =
      { device = "/dev/disk/by-uuid/d32f376d-78ce-4f3c-847e-d0e1b35cfc7d";
        fsType = "btrfs";
      };

	fileSystems."/nix" =
	  { device = "/dev/disk/by-uuid/d32f376d-78ce-4f3c-847e-d0e1b35cfc7d";
        fsType = "btrfs";
        options = [ "subvol=nix" ];
      };

	fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/8650-8200";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

    fileSystems."/home" =
      { device = "/dev/disk/by-uuid/f2922ce9-34d1-4425-9d8c-3c6c00d2b33f";
        fsType = "btrfs";
      };

	swapDevices = [ ];

	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
